Neural Network is a computer model which contains many neurons segregated as layers , there are mainly 3 layers , input output and hidden layers . A neuron is a small computational unit which is connected to other neurons and takes input from them , it has a bias , weights and an activation function . The input in the neuron comes in the form of summation of product of input values and weights and at last bias of the current neuron is added to it , later this value is passed through an activation function in which it decides the final value to output to next neuron or even the decision to whether output the value to the next neuron or not                                                                             
neuron_output = Activationfunction((Input X Weight) + Bias)  

In [1]:
output_layer = []
input_layer=[1,2,3,3.5]
biases=[2,3,.5]
weights=[[.5,.5,.4,.6],
         [.43,.52,.543,.243],
         [.43 ,.54, .75 ,.84]]



In [2]:
for neuron_weights , bias in zip(weights,biases):
    neuron_output = 0
    for inputs,nweights in zip(input_layer,neuron_weights):
        neuron_output+=inputs*nweights
    neuron_output+=bias
    output_layer.append(neuron_output)  
print(output_layer)      

[6.800000000000001, 6.9495000000000005, 7.199999999999999]


Instead of using loops to multiply weights and inputs we can use dot product

In [3]:
import numpy as np



output_layer=[]
for neuron_weight,bias in zip(weights,biases):
    neuron_output = np.dot(neuron_weight,input_layer) + bias
    output_layer.append(neuron_output)    
print(output_layer)

[np.float64(6.800000000000001), np.float64(6.9495000000000005), np.float64(7.199999999999999)]


Batch size mean the total inputs used to train a neural network at once , for example a photo with 28x28  dimensions has 784 grids as input features , if we input the model with only one image than the batch size is one , the neural network does not train properly with it , so if we input 32 image at once that is batch size of 32 it trains the neural network on 32 images at once ,not iteratively but through matrix multiplicatoin and vectors all the 32 inputs are processed at once unlike traditional ml where the model is trained by going through inputs iteratively , also we cannot use all the images at once because that would cause overfitting

So now the input changes from 1d to 2d with the number of rows being the batch size

In [4]:
input_layer=[[1,2,3,3.5],
             [3.2, 5.3,3.4,5.1],
             [2.3,2.4,4.3,4.2],
             [3.3,4.3,2.4,5.3]]

In the weights 2d array each row represent the weights of individual neuron but during matrix multiplication to get the output values of neurons we need each columns to be the weights of individual neuron so use transpose

In [5]:
output_layer=[]
weights = np.transpose(weights)
output_layer = np.dot(input_layer,weights)  + biases
print(output_layer)

[[ 6.8     6.9495  7.2   ]
 [10.67   10.2175 11.572 ]
 [ 8.59    8.5925  9.538 ]
 [ 9.94    9.2461 10.493 ]]


In this output above matrix each row represents the output neurons or the output layers of one batch

Now we add one more layer and the weights and biases keep on incresasing like shown below

In [6]:
input_layer1=[[1,2,3,3.5],
             [3.2, 5.3,3.4,5.1],
             [2.3,2.4,4.3,4.2],
             [3.3,4.3,2.4,5.3]]

biases1=[2,3,.5]
weights1=[[.5,.5,.4,.6],
         [.43,.52,.543,.243],
         [.43 ,.54, .75 ,.84]]

biases2=[2,3,3.8,1.5]
weights2=[[.15,.5,.74,.86],
         [.3,.52,.6543,.243],
         [.243 ,.454, .735 ,.384]]



we try to keep the value ranges of input weights or any other parameters between -1 and 1 mostly because if the values are not in that range after passing through multiple layers,neurons the value may be very big and problem occurs


In [7]:
import numpy as np
np.random.seed(0)

X=[[1,2,3,3.5],
  [3.2, 5.3,3.4,5.1],
  [2.3,2.4,4.3,4.2],
  [3.3,4.3,2.4,5.3]]

class Layer_dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases

Now we can keep on creating layer objects but the input of the next layer must be same as the output of the previous layer for obious reasons

In [8]:
layer1=Layer_dense(4,5)
layer2=Layer_dense(5,32)

layer1.forward(X)
print(layer1.output)

[[ 1.40948745 11.89243132  2.24108282  3.4952175   1.0310096 ]
 [ 2.65688196 18.88030488  3.87098947  8.63413866  5.30560435]
 [ 3.73267301 15.72908197  4.29863757  6.74441603  3.60222958]
 [ 3.73325636 16.81477449  3.31815109  8.90238535  4.46707927]]


ACTIVATION FUNCTIONS

It decides whether to fire the neuron or stay quiet , in other ways whether to allow the processed value in the neuron to pass to the next neuron as input or not , functions like RELU (max(x,0)) , step wise function and sigmoid functions are used

WHY IS ACTIVATION FUNCTION REQUIRED?

if we dont use activation function and just pass the inputXweight + bias to the next neuron then all the neurons will do the same thing so the final output will be a linear funcion like Wx + B so it can only predict values linerly and cannot adapt according to the data required , so to overcome this in between we need to introduce non linearity and activation functions do this

In [9]:
import numpy as np # this block is just to create the dataset

np.random.seed(0)


def create_data(points, classes):
    X = np.zeros((points * classes, 2))
    Y = np.zeros(points * classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points * class_number, points * (class_number + 1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number * 4, (class_number + 1) * 4, points) + np.random.randn(points) * 0.2
        X[ix] = np.c_[r * np.sin(t * 2.5), r * np.cos(t * 2.5)]
        Y[ix] = class_number
    return X, Y

In [16]:
    
X,Y = create_data(100,3) 


class Layer_dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.10*np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases


class Activation_Relu:
    def forward(self,layer_output):
        self.activated_output = np.maximum(0,layer_output)


In [20]:
layer1 = Layer_dense(2,5)   # since the number of data features is 2 (coordinates)
activation1 = Activation_Relu()
layer1.forward(X)
activation1.forward(layer1.output)
layer1output = activation1.activated_output

In [22]:
print(layer1output)

[[0.         0.         0.         0.         0.        ]
 [0.         0.00026099 0.         0.         0.0019636 ]
 [0.         0.00326282 0.00103883 0.         0.00124191]
 ...
 [0.         0.         0.         0.02708142 0.1919911 ]
 [0.00816536 0.         0.         0.09704872 0.12448636]
 [0.00424775 0.         0.         0.08921545 0.14418652]]
